language: php

php:
 - 5.4
 - 5.5

before_script:
 - composer install

script:
 - ./vendor/bin/atoum -bf vendor/autoload.php -d ./Tests/Unit/ -c .atoum.php

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
