language: php

php:
 - 5.5

before_script:
 - composer install

script:
 - make test_unit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
